name = "cf-workers-wechat-gpt"
main = "worker.js"
compatibility_date = "2023-10-30"

kv_namespaces = [
  { binding = "AI_CHAT_HISTORY", id = "your-kv-id-here" }
]

[vars]
WECHAT_TOKEN = ""
USE_OPENAI = "true"
WELCOME_MESSAGE = "感谢关注！我是基于 AI 的智能助手，可以回答您的各种问题。"
CHAT_HISTORY_LIMIT = "2"
# 其他环境变量在 Cloudflare Dashboard 设置